Use commit-and-tag-version for Release Management
eclipse-kuksa/kuksa-android-sdk pull request #32
Opened 2023-11-10 12:20 UTC by Chrylo

- Pushing a tag like release/v0.1.0 will now trigger a release build. The NPM commands should always be used.
- Merging into main will now always trigger a snapshot build of the new version (after bumping). 

Used https://github.com/absolute-version/commit-and-tag-version for the supporting the release process e.g. tagging, committing, bumping versions.

Used https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles for testing the added release markdown doc.

Tested snapshot and release builds here: https://github.com/boschglobal/kuksa-android-sdk/actions/

After merging this:
1) Every Snapshot will be at least a 0.1.1 version
2) We should deploy an official release of 0.1.0

2023-11-10 14:05 UTC, wba2hi requested changes

2023-11-10 14:54 UTC, Chrylo commented on docs/kuksa-sdk_class-diagram.puml
> +        + subscriptions: Collection<Property>
Removed it again. I was already thinking about it.

2023-11-10 14:57 UTC, Chrylo commented on docs/RELEASE.md
> +3) Check if the GitHub package was uploaded succesfully.
My thinking was writing this guide for eclipse repo maintainer (who can also push tags there). The description should still fit then?

2023-11-10 14:58 UTC, Chrylo commented on buildSrc/src/main/kotlin/org/eclipse/kuksa/util/SemanticVersion.kt
> +package org.eclipse.kuksa.util
Just renamed the class :P but yes...

2023-11-13 06:14 UTC, wba2hi commented on .github/workflows/deploy-release.yaml
> +name: deployment
For a better differentiation, we should rename the tasks differently - right now both of them appear as "deployment" in the Github Actions Log:

maybe by removing the root level name it just falls back to the yaml name, whic hwould be totally appropriate here.

2023-11-13 10:48 UTC, wba2hi commented
LGTM

2023-11-13 10:49 UTC, wba2hi commented
@SebastianSchildt @lukasmittag
 
Ticket can be merged

2023-11-13 10:49 UTC, wba2hi approved these changes

2023-11-13 10:51 UTC, SebastianSchildt approved these changes

2023-11-13 10:51 UTC, merged